### ISSUE TITLE
Allow player to pass in front of and behind some objects

### ISSUE THREAD

**Issue by brylie** [OpenLearningQuest/game#6]
There will be game objects that the player can go behind, such as bushes or fences.

## Task

- [ ] the game displays a character with one or more simple objects (e.g., blocks)
- [ ] when the player passes in front of the object (on the Y axis) they appear in front
- [ ] when the player passes behind the object, the object appears in front, with the player remaining visible behind

## Resources

- https://docs.godotengine.org/en/stable/classes/class_ysort.html
