### ISSUE TITLE
Initial dialogue system experiment

### ISSUE THREAD

**Issue by brylie** [OpenLearningQuest/game#7]
We will want to have dialogues in our game to convey the story.

## Task

Create a dialogue experiment such as the following.

- [ ] we can define dialogues in an intuitive manner
- [ ] dialogues may trigger events
- [ ] dialogues may use variables (such as the global state)
- [ ] dialogues can be translated

**Comment by brylie** [comment]
After reviewing [current options for Godot 4.2 dialogue management](https://godotengine.org/asset-library/asset?filter=dialog&category=&godot_version=&cost=&sort=updated), two main options stand out:

- [Dialogic](https://godotengine.org/asset-library/asset/833)
    - [releases](https://github.com/dialogic-godot/dialogic/releases) 
- [DialogueNodes](https://github.com/nagidev/DialogueNodes)
    - [source](https://github.com/nagidev/DialogueNodes)

Dialogic looks fairly mature, but has had a long delay in releasing version 2.0 with Godot 4.x support. So, it's not currently a viable option.

Dialogue Nodes is newer, but supports Godot 4.2. It provides a simple interface for creating branching dialogues, defining variables, creating characters, and simple text effects. For now, I recommend we work with Dialogue Nodes.
